version: '3.2'

services:
  api:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - mongodb
    networks:
      - sail

  mongodb:
    image : mongo
    container_name: mongodb
    env_file:
      - .env
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_DATABASE: unnax_read_dk
    volumes:
      - mongodbvol:/data/db
    ports:
      - 27017:27017
    networks:
      - sail
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    enviromet:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
    volumes:
      - rabbitvol:/var/lib/rabbitmq/
      - rabbitvol:/var/log/rabbitmq
    networks:
      - sail

  celery:
    build: .
    hostname: rabbitmq
    command: celery -A read_unnax worker -l info
    volumes:
      - .:/code
    networks:
      - sail
    depends_on:
      - mongodb
      - rabbitmq
  
  celery-beat:
    build: .
    hostname: rabbitmq
    command: celery -A read_unnax beat -l info
    volumes:
      - .:/code
    networks:
      - sail
    depends_on:
      - mongodb
      - rabbitmq

networks:
  sail:
    driver: bridge

volumes:
  mongodbvol:
    driver: local
  rabbitvol:
    driver: local