version: '3'

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE='unnax_read_dk'
    volumes:
      - .:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
